name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

      - name: Build Frontend
        if: steps.filter.outputs.frontend == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #  git clean -fd removes any untracked files, which helps to maintain consistency
          script: |
            cd /home/ubuntu/Personal-Website
            git reset --hard
            git clean -fd
            git pull
            cd ./frontend
            npm i
            npm run build

      - name: Deploy Frontend
        if: steps.filter.outputs.frontend == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Personal-Website/frontend
            rm -rf /var/www/dist
            mv dist/ /var/www

      - name: Start Backend
        if: steps.filter.outputs.backend == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Personal-Website
            git reset --hard
            git clean -fd
            git pull
            cd ./backend
            source ./venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart personal-website-backend
