name: Build and deploy

on: 
 push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Build Frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #  git clean -fd removes any untracked files, which helps to maintain consistency
        script: |
         cd /home/ubuntu/Personal-Website
         git pull origin main
         git clean -fd
         git status
         cd ./frontend
         npm run build

    - name: Deploy Frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
         cd /home/ubuntu/Personal-Website/frontend
         rm -rf /var/www/dist
         mv dist/ /var/www

    
